apiVersion: storage.kubestash.com/v1alpha1
kind: BackupStorage
metadata:
  name: s3-storage
spec:
  storage:
    provider: s3
    s3:
      bucket: kubestash
      region: us-east-2
      endpoint: https://s3.us-east-2.amazonaws.com
      secretName: aws-s3-secret
      prefix: anisur
  usagePolicy:
    allowedNamespaces:
      from: All
  default: false
  deletionPolicy: WipeOut
