{
 "title": "NooBaa Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "worker",
    "label": "Worker",
    "query": {
     "query": "label_values(kube_node_role{role=~'(worker|infra)'}, node)"
    }
   },
   {
    "name": "rbd_device",
    "label": "rbd Device",
    "query": {
     "query": "label_values(node_disk_read_bytes_total{instance=~\"$worker.*\", device=~\"rbd.*\"}, device)"
    }
   },
   {
    "name": "pvc",
    "label": "ODF PVC Name",
    "query": {
     "query": "label_values(kube_persistentvolumeclaim_info{storageclass=~\"ocs-storagecluster.*\"},persistentvolumeclaim)"
    }
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "ocs_version",
    "query": {
     "query": "label_values(ocs_exporter_version, version)"
    }
   },
   {
    "name": "ceph_version",
    "query": {
     "query": "label_values(ceph_mon_metadata, ceph_version)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Noobaa Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Noobaa Health",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "max(NooBaa_health_status)" }
     ]
    },
    {
     "title": "Buckets",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 2, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "count(NooBaa_bucket_status)" }
     ]
    },
    {
     "title": "Buckets in Error",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(noobaa_bucket_status == 0) or vector(0)"
      }
     ]
    },
    {
     "title": "OBCs",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "NooBaa_num_buckets_claims" }
     ]
    },
    {
     "title": "Object Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "NooBaa_num_objects_buckets_claims"
      }
     ]
    },
    {
     "title": "Quotas Set",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 10, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(NooBaa_bucket_size_quota > 0) or vector(0)"
      }
     ]
    },
    {
     "title": "Savings",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(NooBaa_object_savings_logical_size - NooBaa_object_savings_physical_size) "
      }
     ]
    },
    {
     "title": "Data Reduction",
     "type": "stat",
     "description": "Data reduction ratio",
     "gridPos": { "h": 4, "w": 2, "x": 14, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "NooBaa_reduction_ratio" }
     ]
    },
    {
     "title": "Capacity Used",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 2, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "NooBaa_system_capacity" }
     ]
    },
    {
     "title": "Usage by bucketclass",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max by(bucket_class) (NooBaa_bucket_class_capacity_usage)",
       "legendFormat": "{{bucket_class}}"
      }
     ]
    },
    {
     "title": "Total Noobaa CPU Core Usage",
     "type": "timeseries",
     "description": "Sum of cpu usage for ALL noobaa daemons expessed as a percentage of cpu cores (i.e. > 100% = 1 core, 200% = 2 cores)",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",container=~\"noobaa|core|db|endpoint\", namespace=\"noobaa\"}[1m]))",
       "legendFormat": "Total CPU"
      }
     ]
    },
    {
     "title": "Noobaa Provider R/W OPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "round(sum by(namespace, managedBy, job, service) (rate(NooBaa_providers_ops_read_num[1m])),1)",
       "legendFormat": "Read OPs "
      },
      {
       "expr": "round(sum by(namespace, managedBy, job, service) (rate(NooBaa_providers_ops_write_num[1m])),1)",
       "legendFormat": "Write OPs"
      }
     ]
    },
    {
     "title": "Noobaa Provider R/W Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(namespace, managedBy, job, service) (rate(NooBaa_providers_bandwidth_read_size[1m]))",
       "legendFormat": "Read Throughput"
      },
      {
       "expr": "sum by(namespace, managedBy, job, service) (rate(NooBaa_providers_bandwidth_write_size[1m]))",
       "legendFormat": "Write Throughput"
      }
     ]
    },
    {
     "title": "Capacity Used vs Object count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "max(noobaa_total_usage)", "legendFormat": "Total Used" },
      {
       "expr": "max(job:noobaa_total_object_count:sum)",
       "legendFormat": "Object Count"
      }
     ]
    },
    {
     "title": "Object Size Distribution",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "NooBaa_object_histo > 0", "legendFormat": "{{size}}" }
     ]
    },
    {
     "title": "Noobaa Endpoints Active",
     "type": "timeseries",
     "description": "Count of the number of noobaa endpoints in the cluster. The red line depicts the scaling limit.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count(container_last_seen{pod=~\"noobaa-endpoint.*\", namespace=\"noobaa\",image!=\"\"})",
       "legendFormat": "Endpoints Active"
      }
     ]
    }
   ]
  }
 ]
}